apiVersion: sro.openshift.io/v1beta1
kind: SpecialResourceModule
metadata:
  name: acm-ice
spec:
  look: atthisfield
  namespace: acm-ice
  chart:
    name: acm-ice
    version: 0.0.1
    repository:
      name: chart
      url: file:///charts/example
  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    buildArgs:
      - name: DRIVER_VER
        value: "1.6.4"
    #registry: image-registry.openshift-image-registry.svc:5000/acm-ice
    registry: quay.io/pacevedo
  watch:
    - path: "$.metadata.labels.openshiftVersion"
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      name: local-cluster
