apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{.Values.specialResourceModule.metadata.name}}-{{.Values.groupName.driverContainer}}
  name: {{.Values.specialResourceModule.metadata.name}}-{{.Values.groupName.driverContainer}}
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{.Values.specialResourceModule.metadata.name}}-{{.Values.groupName.driverBuild}}
  name: {{.Values.specialResourceModule.metadata.name}}-{{.Values.groupName.driverBuild}}
  annotations:
    specialresource.openshift.io/wait: "true"
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    git:
      ref: {{.Values.specialResourceModule.spec.driverContainer.source.git.ref}}
      uri: {{.Values.specialResourceModule.spec.driverContainer.source.git.uri}}
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile.SRO
#      from:
#        kind: "ImageStreamTag"
#        name: "driver-container-base:v{{.Values.kernelFullVersion}}"
#        namespace: "driver-container-base"
      buildArgs:
        - name: "IMAGE"
          value: {{ .Values.driverToolkitImage  }}
        {{- range $arg := .Values.buildArgs }}
        - name: {{ $arg.name }}
          value: {{ $arg.value }}
        {{- end }}
        - name: KVER
          value: {{ .Values.kernelFullVersion }}
  output:
    to:
      kind: ImageStreamTag
      name: {{.Values.specialResourceModule.metadata.name}}-{{.Values.groupName.driverContainer}}:v{{.Values.kernelFullVersion}}

